// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task_update_service.proto

package ie.nci.distributedsystems.task_update_service;

public interface GetTaskUpdatesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taskupdateservice.GetTaskUpdatesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 task_id = 1;</code>
   */
  int getTaskId();
}
