// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task_update_service.proto

package ie.nci.distributedsystems.task_update_service;

public final class TaskUpdate {
  private TaskUpdate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_taskupdateservice_UpdateTaskResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_taskupdateservice_UpdateTaskResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_taskupdateservice_UpdateTaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_taskupdateservice_UpdateTaskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_taskupdateservice_GetTaskUpdatesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_taskupdateservice_GetTaskUpdatesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_taskupdateservice_GetTaskUpdatesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_taskupdateservice_GetTaskUpdatesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031task_update_service.proto\022\021taskupdates" +
      "ervice\032\035task_management_service.proto\"$\n" +
      "\022UpdateTaskResponse\022\016\n\006status\030\001 \001(\t\">\n\021U" +
      "pdateTaskRequest\022)\n\004task\030\001 \001(\0132\033.taskman" +
      "agementservice.Task\"(\n\025GetTaskUpdatesReq" +
      "uest\022\017\n\007task_id\030\001 \001(\005\"C\n\026GetTaskUpdatesR" +
      "esponse\022)\n\004task\030\001 \001(\0132\033.taskmanagementse" +
      "rvice.Task2\334\001\n\021TaskUpdateService\022\\\n\013Upda" +
      "teTasks\022$.taskupdateservice.UpdateTaskRe" +
      "quest\032%.taskupdateservice.UpdateTaskResp" +
      "onse(\001\022i\n\016GetTaskUpdates\022(.taskupdateser" +
      "vice.GetTaskUpdatesRequest\032).taskupdates" +
      "ervice.GetTaskUpdatesResponse(\0010\001B=\n-ie." +
      "nci.distributedsystems.task_update_servi" +
      "ceB\nTaskUpdateP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ie.nci.distributedsystems.task_management_service.TaskManagement.getDescriptor(),
        }, assigner);
    internal_static_taskupdateservice_UpdateTaskResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_taskupdateservice_UpdateTaskResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_taskupdateservice_UpdateTaskResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_taskupdateservice_UpdateTaskRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_taskupdateservice_UpdateTaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_taskupdateservice_UpdateTaskRequest_descriptor,
        new java.lang.String[] { "Task", });
    internal_static_taskupdateservice_GetTaskUpdatesRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_taskupdateservice_GetTaskUpdatesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_taskupdateservice_GetTaskUpdatesRequest_descriptor,
        new java.lang.String[] { "TaskId", });
    internal_static_taskupdateservice_GetTaskUpdatesResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_taskupdateservice_GetTaskUpdatesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_taskupdateservice_GetTaskUpdatesResponse_descriptor,
        new java.lang.String[] { "Task", });
    ie.nci.distributedsystems.task_management_service.TaskManagement.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
