// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task_update_service.proto

package ie.nci.distributedsystems.task_update_service;

public interface UpdateTaskRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taskupdateservice.UpdateTaskRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.taskmanagementservice.Task task = 1;</code>
   */
  boolean hasTask();
  /**
   * <code>.taskmanagementservice.Task task = 1;</code>
   */
  ie.nci.distributedsystems.task_management_service.Task getTask();
  /**
   * <code>.taskmanagementservice.Task task = 1;</code>
   */
  ie.nci.distributedsystems.task_management_service.TaskOrBuilder getTaskOrBuilder();
}
