// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task_update_service.proto

package ie.nci.distributedsystems.task_update_service;

public interface UpdateTaskResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taskupdateservice.UpdateTaskResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
