// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task.management_service.proto

package ie.nci.distributedsystems.task_management_service;

public interface AddTaskResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taskmanagementservice.AddTaskResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 task_id = 1;</code>
   */
  int getTaskId();
}
