// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task.management_service.proto

package ie.nci.distributedsystems.task_management_service;

public interface AddTaskRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taskmanagementservice.AddTaskRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.taskmanagementservice.Task task = 1;</code>
   */
  boolean hasTask();
  /**
   * <code>.taskmanagementservice.Task task = 1;</code>
   */
  ie.nci.distributedsystems.task_management_service.Task getTask();
  /**
   * <code>.taskmanagementservice.Task task = 1;</code>
   */
  ie.nci.distributedsystems.task_management_service.TaskOrBuilder getTaskOrBuilder();
}
