// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task.management_service.proto

package ie.nci.distributedsystems.task_management_service;

public interface AddTaskResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taskmanagementservice.AddTaskResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string task_id = 1;</code>
   */
  java.lang.String getTaskId();
  /**
   * <code>string task_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();
}
