// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task_management_service.proto

package ie.nci.distributedsystems.task_management_service;

public interface GetTasksByDateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taskmanagementservice.GetTasksByDateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.taskmanagementservice.Date date = 1;</code>
   */
  boolean hasDate();
  /**
   * <code>.taskmanagementservice.Date date = 1;</code>
   */
  ie.nci.distributedsystems.task_management_service.Date getDate();
  /**
   * <code>.taskmanagementservice.Date date = 1;</code>
   */
  ie.nci.distributedsystems.task_management_service.DateOrBuilder getDateOrBuilder();
}
