// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task.management_service.proto

package ie.nci.distributedsystems.task_management_service;

public interface GetTasksByDateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taskmanagementservice.GetTasksByDateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Timestamp date = 1;</code>
   */
  boolean hasDate();
  /**
   * <code>.google.protobuf.Timestamp date = 1;</code>
   */
  com.google.protobuf.Timestamp getDate();
  /**
   * <code>.google.protobuf.Timestamp date = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDateOrBuilder();
}
