// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task.management_service.proto

package ie.nci.distributedsystems.task_management_service;

public interface TaskOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taskmanagementservice.Task)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string description = 3;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>.google.protobuf.Timestamp due_date = 4;</code>
   */
  boolean hasDueDate();
  /**
   * <code>.google.protobuf.Timestamp due_date = 4;</code>
   */
  com.google.protobuf.Timestamp getDueDate();
  /**
   * <code>.google.protobuf.Timestamp due_date = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDueDateOrBuilder();

  /**
   * <code>string assigned_user = 5;</code>
   */
  java.lang.String getAssignedUser();
  /**
   * <code>string assigned_user = 5;</code>
   */
  com.google.protobuf.ByteString
      getAssignedUserBytes();
}
