// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task_deletion_service.proto

package ie.nci.distributedsystems.task_deletion_service;

public interface DeleteTaskResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taskdeletionservice.DeleteTaskResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
