// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task_deletion_service.proto

package ie.nci.distributedsystems.task_deletion_service;

public interface DeleteTaskRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taskdeletionservice.DeleteTaskRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 task_id = 1;</code>
   */
  int getTaskId();
}
