// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task_deletion_service.proto

package ie.nci.distributedsystems.task_deletion_service;

public final class TaskDeletion {
  private TaskDeletion() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_taskdeletionservice_DeleteTaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_taskdeletionservice_DeleteTaskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_taskdeletionservice_DeleteTasksRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_taskdeletionservice_DeleteTasksRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_taskdeletionservice_DeleteTaskResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_taskdeletionservice_DeleteTaskResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033task_deletion_service.proto\022\023taskdelet" +
      "ionservice\"$\n\021DeleteTaskRequest\022\017\n\007task_" +
      "id\030\001 \001(\005\"%\n\022DeleteTasksRequest\022\017\n\007task_i" +
      "d\030\001 \001(\005\"$\n\022DeleteTaskResponse\022\016\n\006status\030" +
      "\001 \001(\t2\327\001\n\023TaskDeletionService\022]\n\nDeleteT" +
      "ask\022&.taskdeletionservice.DeleteTaskRequ" +
      "est\032\'.taskdeletionservice.DeleteTaskResp" +
      "onse\022a\n\013DeleteTasks\022\'.taskdeletionservic" +
      "e.DeleteTasksRequest\032\'.taskdeletionservi" +
      "ce.DeleteTaskResponse(\001BA\n/ie.nci.distri" +
      "butedsystems.task_deletion_serviceB\014Task" +
      "DeletionP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_taskdeletionservice_DeleteTaskRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_taskdeletionservice_DeleteTaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_taskdeletionservice_DeleteTaskRequest_descriptor,
        new java.lang.String[] { "TaskId", });
    internal_static_taskdeletionservice_DeleteTasksRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_taskdeletionservice_DeleteTasksRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_taskdeletionservice_DeleteTasksRequest_descriptor,
        new java.lang.String[] { "TaskId", });
    internal_static_taskdeletionservice_DeleteTaskResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_taskdeletionservice_DeleteTaskResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_taskdeletionservice_DeleteTaskResponse_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
